-- donations.sql
-- Auto-generated by Donation Management System
-- Last updated: 2026-05-29T09:33:17.622Z
--
-- Each row is one donation INSERT statement, sorted by amount DESC.
INSERT INTO donations (id, name, nameGu, city, cityGu, message, messageGu, amount, date, profileImage) VALUES (1, 'gbrf', 'gbrf', '454dsa', '454dsa', 'fedfvd', 'fedfvd', 164, '2026-05-29T09:33:17.621Z', NULL);
